import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex z-50">
          <div className="hidden sm:block w-[300px] bg-[#5f4a78] h-screen fixed">
            <nav className="p-6">
              <ul className="space-y-4">
                <li>
                  <Link href="/contracts">
                    <span className="text-white hover:text-gray-200 transition-colors text-lg">
                      Contracts
                    </span>
                  </Link>
                </li>
                <li>
                  <Link href="/templates">
                    <span className="text-white hover:text-gray-200 transition-colors text-lg">
                      Templates
                    </span>
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
